version: '2'
services:
  dnsmasq:
    build:
      context: ../docker.d
      dockerfile: Dockerfile.dnsmask
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    command: --log-facility=-
    volumes:
      - ../etc/dnsmasq.conf:/etc/dnsmasq.conf
