version: '3.9'

services:

  nginx:
    #image: hello-world
    build:
      context: ../docker.d
      dockerfile: Dockerfile.nginx
    # image: nginx
    volumes:
      - type: bind
        source: ../etc/nginx/conf.d
        target: /etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - python-httpserver
    networks:
      - default
